spring.application.name=todo-list

spring.jackson.serialization.indent-output=true
spring.datasource.url=jdbc:mysql://localhost:3306/todos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
api.security.token.secret=minha-chave-secreta-muito-segura-123
